In [3]:
from __future__ import print_function
import numpy as np

In [4]:
print ('hello world!')

hello world!


In [11]:
stringVariable = 'Hello #1!'
print (stringVariable)
type (stringVariable)


Hello #1!


str

In [15]:
floatVariable = 3.082049032
print (floatVariable)
type (floatVariable)


3.082049032


float

In [16]:
intVariable = 3
type (intVariable)

int

In [17]:
floatVariable * intVariable

9.246147096

In [21]:
print (intVariable, floatVariable)
print("Let's print an integer %s and a float %s" %(intVariable, floatVariable))
print("Let's print an integer %s and a float %.2f" %(intVariable, floatVariable))

3 3.082049032
Let's print an integer 3 and a float 3.082049032
Let's print an integer 3 and a float 3.08


In [30]:
print("Let's print an integer {x} and a float {y} and an integer again {x}"\
      .format(x=intVariable, y=floatVariable))
print("Let's print an integer {0:d} and a float {1:5f} and an integer again {0:.2f}"\
      .format(intVariable, floatVariable))

Let's print an integer 3 and a float 3.082049032 and an integer again 3
Let's print an integer 3 and a float 3.082049 and an integer again 3.00


In [33]:
isinstance(intVariable, int) or isinstance(intVariable, float)


True

In [34]:
isinstance(intVariable, int) | isinstance(intVariable, float)

True

In [36]:
isinstance(intVariable, float) >0

False

In [41]:
True == 0, False == 0, True == 1, False == 1

(False, True, True, False)

In [47]:
if True + False:
    print ('it is!')

it is!


In [52]:
if (1>0) + (6>3): #true + False
    print ('it is!')

it is!


In [53]:
np.array([True, True, False]) * np.array([True, False, True])

array([ True, False, False], dtype=bool)

In [54]:
type (True)

bool

In [61]:
if (1>0):
    print ('it is!')
else:
    print ('it aint!')

    
if (1>7):
    print ('it is!')
else:
    print ('it aint!')

it is!
it aint!


In [68]:
alist = [0,1,3.2, 'hello']

In [69]:
type (alist)

list

In [70]:
alist.append("i'm a string!")

In [71]:
alist

[0, 1, 3.2, 'hello', "i'm a string!"]

In [73]:
alist.append([2,4,1.5,8])

In [75]:
alist
#showing how lists can house lists

[0, 1, 3.2, 'hello', "i'm a string!", [2, 4, 1.5, 8]]

In [79]:
alist.append('''im a string\n on two lines!''')

In [80]:
alist

[0,
 1,
 3.2,
 'hello',
 "i'm a string!",
 [2, 4, 1.5, 8],
 'im a string\n\n    on two lines!',
 'im a string\n on two lines!',
 'im a string\n on two lines!']

In [81]:
alist

[0,
 1,
 3.2,
 'hello',
 "i'm a string!",
 [2, 4, 1.5, 8],
 'im a string\n\n    on two lines!',
 'im a string\n on two lines!',
 'im a string\n on two lines!']

In [82]:
alist[0] = "world"

In [83]:
alist

['world',
 1,
 3.2,
 'hello',
 "i'm a string!",
 [2, 4, 1.5, 8],
 'im a string\n\n    on two lines!',
 'im a string\n on two lines!',
 'im a string\n on two lines!']

In [85]:
alist[2] + alist[0][0]

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [86]:
aTuple = (0,1)

In [87]:
type(aTuple)

tuple

In [88]:
aTuple = aTuple * 2 
aTuple

(0, 1, 0, 1)

In [91]:
stringVariable * 20

'Hello #1!Hello #1!Hello #1!Hello #1!Hello #1!Hello #1!Hello #1!Hello #1!Hello #1!Hello #1!Hello #1!Hello #1!Hello #1!Hello #1!Hello #1!Hello #1!Hello #1!Hello #1!Hello #1!Hello #1!'

In [92]:
np.array([0., 2., .3, 4])

array([ 0. ,  2. ,  0.3,  4. ])

In [94]:
np.array([0., 2., .3, 4]) * 2
#does math on the items within the array, rather than multiplying the element itself like the stringVariable above

array([ 0. ,  4. ,  0.6,  8. ])

In [100]:
np.zeros(0)

array([], dtype=float64)

In [118]:
a = np.int8(127)
#127 is the largest number you can use to use with an 8 bit funciton
2**16 /2 - 1 #capacity for int8

32767

In [119]:
a

127

In [120]:
b = a = np.int8(129)

In [121]:
b

-127

In [123]:
alist

['world',
 1,
 3.2,
 'hello',
 "i'm a string!",
 [2, 4, 1.5, 8],
 'im a string\n\n    on two lines!',
 'im a string\n on two lines!',
 'im a string\n on two lines!']

In [124]:
alist[:3]
#: means - everything starting from the first element, all the way up to, but excluding 3

['world', 1, 3.2]

In [126]:
np.array(alist[:3])
#arrays have to have the same type of objects - cannot be mixed

array(['world', '1', '3.2'], 
      dtype='|S5')

In [132]:
emptyAr = np.zeros(100,int)

In [133]:
emptyAr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [142]:
emptyAr = np.ones((10, 20), int)

In [143]:
emptyAr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [144]:
emptyAr.shape
#tells you what shape your array has. helpful for clarifying which axis is which

(10, 20)

In [146]:
stringVariable

'Hello #1!'

In [147]:
stringVariable.strip()

'Hello #1!'

In [149]:
stringVariable.strip().strip("!")

'Hello #1'

In [153]:
"~".join(stringVariable.strip().strip("!").split()) #default split happens at the space

'Hello~#1'

In [157]:
" ".join(stringVariable.strip().strip("!").split()).lower().replace("#", "9").replace("l", "R")

'heRRo 91'

In [164]:
dictVariable = {'k1': 1.0
               'k2': 2.34}

SyntaxError: invalid syntax (<ipython-input-164-458d2c2de7d8>, line 2)

In [160]:
dictVariable{} = {}
for i in range (10):
    dictVariable[i] = i**2

In [161]:
dictVariable

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [165]:
dateTime?

Object `dateTime` not found.


In [166]:
#just finshed the first hello good morning exercise

In [167]:
np.random.seed(999)
anArray = np.random.randn(30). reshape(10,3)

In [170]:
anArray

array([[ 0.12715784,  1.40189088,  0.31481499],
       [-0.85844916, -0.26613444, -0.64890071],
       [ 1.56626757, -2.09137019,  1.45632806],
       [ 0.94529342, -0.40020119,  0.3152273 ],
       [-1.11006083, -0.58482153, -0.18840956],
       [ 0.81302365, -0.16130472,  1.60087155],
       [ 0.98434258, -0.83544737, -0.18664934],
       [-0.85806707, -0.75977816, -1.51205424],
       [ 1.74777474,  2.13005498,  0.07115422],
       [-1.84164224, -0.3525907 , -0.40890379]])

In [173]:
anArray[2:5]

array([[ 1.56626757, -2.09137019,  1.45632806],
       [ 0.94529342, -0.40020119,  0.3152273 ],
       [-1.11006083, -0.58482153, -0.18840956]])

In [174]:
anArray[-2]

array([ 1.74777474,  2.13005498,  0.07115422])

In [178]:
anArray[2:5, 1:3]
#think about this as (x, y) coordinates that you're calling up in this larger array
#this one is saying call up rows 3 to 5, and columns 2 to 3

array([[-2.09137019,  1.45632806],
       [-0.40020119,  0.3152273 ],
       [-0.58482153, -0.18840956]])

In [180]:
anArray[0:100:2,0]

array([], dtype=float64)

In [181]:
np.random.seed(999)
anArray2 = np.random.randint(1, 30, 30). reshape(2,15)


In [188]:
anArray2

array([[ 1, 29,  6,  2,  9,  2, 28, 26, 20, 17, 14, 22,  9,  9, 17],
       [ 6,  3, 12, 12, 22, 24,  5, 27,  7, 19,  8,  7, 18,  6, 20]])

In [183]:
anArray2 > 5

array([[False,  True,  True, False,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True]], dtype=bool)

In [189]:
np.where(anArray2>5)[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [190]:
anArray2[0][1]

29

In [191]:
anArray2.T
# T = transpose

array([[ 1,  6],
       [29,  3],
       [ 6, 12],
       [ 2, 12],
       [ 9, 22],
       [ 2, 24],
       [28,  5],
       [26, 27],
       [20,  7],
       [17, 19],
       [14,  8],
       [22,  7],
       [ 9, 18],
       [ 9,  6],
       [17, 20]])

In [195]:
anArray2.astype(float).astype(int) #changing type of info to floats.then back to integers

array([[ 1, 29,  6,  2,  9,  2, 28, 26, 20, 17, 14, 22,  9,  9, 17],
       [ 6,  3, 12, 12, 22, 24,  5, 27,  7, 19,  8,  7, 18,  6, 20]])

In [196]:
#assignment before the break for PIZZA
thisArray = np.array(range(1,11))
print (thisArray)

[ 1  2  3  4  5  6  7  8  9 10]


In [219]:
(thisArray % 2) == 0

array([False,  True, False,  True, False,  True, False,  True, False,  True], dtype=bool)

In [220]:
evennumbers = thisArray[1:100:2]

In [221]:
evennumbers

array([ 2,  4,  6,  8, 10])

In [223]:
evennumbers[::-1]

array([10,  8,  6,  4,  2])

In [224]:
evennumbers[::-1] + 1

array([11,  9,  7,  5,  3])

In [225]:
#resume to lesson

In [227]:
np.vstack(np.where(anArray>5)).T

array([], shape=(0, 2), dtype=int64)

In [230]:
#improper way to call a function, but this is a compact way of writing them should you need to
pr = lambda x, y: x * y

In [231]:
pr(3.0, 3.0)

9.0

In [236]:
def pr (x,y = 2.0):
    '''
    multiplying the arguments
    Arguments:
        x: float
        y: float (optional, default value 2.0)
    return:
        products of the arguments
    '''
    return x * y

In [237]:
pr(3.0)

6.0

In [238]:
dataAr

NameError: name 'dataAr' is not defined

In [241]:
def extractEvenReverse(dataAr):
    '''Extracts values from array and reverses it
    Arguments:
    dataAr: numpy array
    '''
    return dataAt[not (dataAt % 2 == 0)]

In [243]:
extractEvenReverse(np.arrange(1:11))

SyntaxError: invalid syntax (<ipython-input-243-5f4897dceb7c>, line 1)

In [244]:
import ispalindrome 
from ispalindrome import lookForPal

lookForPal('Hannah')

ImportError: No module named ispalindrome

In [272]:
def lookforpal(text):
    if text.lower()==text.lower()[::-1]:
        message = ("Palindrome")
    else:
        message = ("NOT Palindrome")
    return [message]

In [273]:
lookforpal("tacocat")

['Palindrome']

In [274]:
lookforpal("blue")

['NOT Palindrome']

In [275]:
!curl -O https://raw.githubusercontent.com/fedhere/PyBOOT/master/busBusses.npy
!curl -O https://raw.githubusercontent.com/fedhere/PyBOOT/master/busTimeTable.npy

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
120   240  120   240    0     0    904      0 --:--:-- --:--:-- --:--:-- 10000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
105  1680  105  1680    0     0   7651      0 --:--:-- --:--:-- --:--:-- 70000


In [276]:
tt = np.load("busTimeTable.npy")

In [277]:
busses = np.load("busBusses.npy")

In [278]:
busses

array([ 77,  72,  79,  97,  85,  57,  86,  96,  31,  76,  33,  98, 109,
       108,  52,  92,  58,  94,  66, 104])

In [279]:
tt.shape

(20, 10)

In [286]:
hours = range(1,11)

In [287]:
hours

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [288]:
tt

array([[  91.82869011,   72.99278771,   96.74459251,   73.41298391,
          85.58215726,  101.38226456,   96.97680737,   95.56072596,
          77.87195303,   78.37553397],
       [  61.03022409,   60.00463334,   67.86228679,   41.10873249,
          53.37659575,   36.91790247,   53.62835897,   55.73660035,
          58.56814116,   54.98889748],
       [  60.98477297,   45.55742203,   45.88400007,   66.16346096,
          60.03163411,   50.85322708,   45.37677315,   53.8142472 ,
          54.54569551,   60.64418839],
       [  87.98620643,   55.8021912 ,   81.02751282,   66.19019631,
          53.30000683,   67.55780543,   74.38103569,   71.13924744,
          87.67477883,   67.09783283],
       [  73.8097995 ,   79.25914025,   86.31085813,   99.77766307,
          90.29078454,   84.37561182,   95.84112464,   84.50840611,
          97.12166748,  105.17515918],
       [  77.14467806,   71.12444623,   52.12373301,   73.45946947,
          91.36942688,   72.86854378,   68.71403738,   72

In [293]:
tt.mean()

68.884458640080283

In [289]:
tt.mean(axis = 0)

array([ 66.89079118,  71.58962256,  69.06093555,  68.20293716,
        68.35553274,  69.88235848,  69.07994486,  69.5488946 ,
        65.98370986,  70.24985942])

In [290]:
hours[tt.mean(axis = 0).argmax()]

2

In [295]:
print("Avg bus time:{}".format(tt.mean()))


Avg bus time:68.8844586401


In [296]:
tt.mean(axis = 0) == tt.mean(axis = 0).max()

array([False,  True, False, False, False, False, False, False, False, False], dtype=bool)

In [297]:
busses[tt.mean(axis = 0) == tt.mean(axis = 0).max()]

/opt/rh/anaconda/root/envs/PUI2016_Python2/lib/python2.7/site-packages/ipykernel/__main__.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 20 but corresponding boolean dimension is 10
  if __name__ == '__main__':


array([72])

In [298]:
for i in range (10):
    print (i)

0
1
2
3
4
5
6
7
8
9


In [303]:
for i,e in enumerate(['cat', 'dog', 32]):
    print (i,e)

0 cat
1 dog
2 32


In [309]:
for i in range (10):
    print ("The number was %s"%i)

The number was 0
The number was 1
The number was 2
The number was 3
The number was 4
The number was 5
The number was 6
The number was 7
The number was 8
The number was 9


In [310]:
["The number was %s" %i for i in range(10]

SyntaxError: invalid syntax (<ipython-input-310-006fe7d27fd6>, line 1)

In [313]:
import pylab as pl
#could also run as from pylab import plot to use only a portion of pylab

#
x = np.arange(100)
np.random.seed(999)
y = np.random.randn(100) + np.sqrt(x)


In [315]:
fig = []
    
    
for i in range (2):
    fig.append(pl.figure(figsize=(10,2)))
    fig[-1].add_subplot(2,1,i+1)
    pl.plot(x,y)

In [316]:
rcParams

NameError: name 'rcParams' is not defined